import {
    Profile,
    Client,
    Task,
    ActivityLogEntry,
    License,
    TaxRulebookConfig,
    BillingPlan,
    Invoice,
    Payment,
    PaymentAllocation,
} from './types';

// ========== PROFILES ==========
export const profiles: Profile[] = [
    {
        id: 'u-admin-001',
        full_name: 'Людмила',
        role: 'admin',
        email: 'liudmyla@taskcontrol.ua',
        phone: '+380958646908',
        avatar_url: '',
        is_active: true,
        created_at: '2023-01-15T10:00:00Z',
    },
    {
        id: 'u-acc-001',
        full_name: 'Марія Коваленко',
        role: 'accountant',
        email: 'maria@taskcontrol.ua',
        phone: '+380671112233',
        avatar_url: '',
        is_active: true,
        created_at: '2023-02-01T09:00:00Z',
    },
    {
        id: 'u-acc-002',
        full_name: 'Олексій Дорошенко',
        role: 'accountant',
        email: 'alex@taskcontrol.ua',
        phone: '+380931234567',
        avatar_url: '',
        is_active: true,
        created_at: '2023-03-01T09:00:00Z',
    },
    {
        id: 'u-acc-003',
        full_name: 'Сара Яценко',
        role: 'accountant',
        email: 'sarah@taskcontrol.ua',
        phone: '+380951234567',
        avatar_url: '',
        is_active: true,
        created_at: '2023-04-01T09:00:00Z',
    },
    {
        id: 'u-acc-004',
        full_name: 'Дмитро Василенко',
        role: 'accountant',
        email: 'dmytro@taskcontrol.ua',
        phone: '+380661234567',
        avatar_url: '',
        is_active: true,
        created_at: '2023-05-01T09:00:00Z',
    },
];

export const admin = profiles[0];
export const accountants = profiles.filter(p => p.role === 'accountant');

const daysFromNow = (days: number, hour = 10): string => {
    const date = new Date();
    date.setDate(date.getDate() + days);
    date.setHours(hour, 0, 0, 0);
    return date.toISOString();
};

export const taxRulebook: TaxRulebookConfig = {
    year: 2026,
    minimum_wage_on_january_1: 8647,
    single_tax_multipliers: {
        single_tax_group1: 167,
        single_tax_group2: 834,
        single_tax_group3: 1167,
        single_tax_group4: 1167,
    },
    vat_registration_threshold: 1_000_000,
};

// ========== CLIENTS ==========
export const clients: Client[] = [
    {
        id: 'c-001',
        name: 'Забіяка',
        type: 'LLC',
        tax_id_type: 'edrpou',
        tax_id: '37300216',
        status: 'active',
        tax_system: 'general_vat',
        is_vat_payer: true,
        contact_phone: '+380441234567',
        contact_email: 'info@techflow.ua',
        employee_count: 15,
        industry: 'Виробництво м\'ясних продуктів',
        created_at: '2023-05-01T10:00:00Z',
        updated_at: '2023-10-15T10:00:00Z',
        accountants: [profiles[1]],
    },
    {
        id: 'c-002',
        name: 'Трачук В.Л',
        type: 'FOP',
        tax_id_type: 'ipn',
        tax_id: '3012456789',
        status: 'onboarding',
        tax_system: 'single_tax_group3_vat',
        is_vat_payer: true,
        income_limit: 8300000,
        income_limit_source: 'rulebook',
        contact_email: 'studio@design-a.ua',
        industry: 'Програміст',
        created_at: '2023-09-01T10:00:00Z',
        updated_at: '2023-10-18T10:00:00Z',
        accountants: [profiles[2]],
    },
    {
        id: 'c-003',
        name: 'Бащук Олег Ярославович',
        type: 'FOP',
        tax_id_type: 'ipn',
        tax_id: '2876501943',
        status: 'active',
        tax_system: 'single_tax_group2',
        is_vat_payer: false,
        income_limit: 6200000,
        income_limit_source: 'rulebook',
        contact_phone: '+380671234567',
        industry: 'Роздрібна торгівля',
        employee_count: 5,
        created_at: '2023-03-10T10:00:00Z',
        updated_at: '2023-10-10T10:00:00Z',
        accountants: [profiles[1]],
    },
    {
        id: 'c-004',
        name: 'Green Earth NGO',
        type: 'NGO',
        tax_id_type: 'edrpou',
        tax_id: '22018827',
        status: 'active',
        tax_system: 'non_profit',
        is_vat_payer: false,
        contact_email: 'info@greenearth.ua',
        industry: 'Некомерційна',
        created_at: '2023-04-15T10:00:00Z',
        updated_at: '2023-10-12T10:00:00Z',
        accountants: [profiles[2]],
    },
    {
        id: 'c-005',
        name: 'Nordic Objects',
        type: 'LLC',
        tax_id_type: 'edrpou',
        tax_id: '55410233',
        status: 'active',
        tax_system: 'general_vat',
        is_vat_payer: true,
        contact_email: 'hello@nordic.ua',
        industry: 'E-commerce',
        employee_count: 8,
        created_at: '2023-06-01T10:00:00Z',
        updated_at: '2023-10-14T10:00:00Z',
        accountants: [profiles[3]],
    },
    {
        id: 'c-006',
        name: 'Alpha Stream',
        type: 'FOP',
        tax_id_type: 'ipn',
        tax_id: '2992001456',
        status: 'active',
        tax_system: 'single_tax_group3',
        is_vat_payer: false,
        income_limit: 7900000,
        income_limit_source: 'rulebook',
        contact_email: 'alpha@stream.ua',
        industry: 'SaaS',
        created_at: '2023-07-01T10:00:00Z',
        updated_at: '2023-10-15T10:00:00Z',
        accountants: [profiles[2]],
    },
    {
        id: 'c-007',
        name: 'Bright Roof',
        type: 'FOP',
        tax_id_type: 'ipn',
        tax_id: '3157789342',
        status: 'onboarding',
        tax_system: 'single_tax_group3',
        is_vat_payer: false,
        income_limit: 7800000,
        income_limit_source: 'rulebook',
        industry: 'Будівництво',
        created_at: '2023-10-10T10:00:00Z',
        updated_at: '2023-10-18T10:00:00Z',
        accountants: [profiles[1]],
    },
    {
        id: 'c-008',
        name: 'Cafe Aroma',
        type: 'FOP',
        tax_id_type: 'ipn',
        tax_id: '3314456621',
        status: 'active',
        tax_system: 'single_tax_group2',
        is_vat_payer: false,
        income_limit: 6100000,
        income_limit_source: 'rulebook',
        contact_phone: '+380951112233',
        industry: 'HoReCa',
        employee_count: 3,
        created_at: '2023-02-20T10:00:00Z',
        updated_at: '2023-10-17T10:00:00Z',
        accountants: [profiles[1]],
    },
    {
        id: 'c-009',
        name: 'Velvet Inc.',
        type: 'LLC',
        tax_id_type: 'edrpou',
        tax_id: '66789944',
        status: 'active',
        tax_system: 'general_vat',
        is_vat_payer: true,
        contact_email: 'office@velvet.ua',
        industry: 'Виробництво',
        employee_count: 22,
        created_at: '2023-01-20T10:00:00Z',
        updated_at: '2023-10-16T10:00:00Z',
        accountants: [profiles[4]],
    },
];

// ========== LICENSES ==========
export const licenses: License[] = [
    {
        id: 'lic-001',
        client_id: 'c-003',
        responsible_id: 'u-acc-001',
        type: 'alcohol_retail',
        number: 'ALC-RT-23-1189',
        issuing_authority: 'ГУ ДПС у м. Києві',
        place_of_activity: 'м. Київ, вул. Антоновича, 12',
        status: 'expiring',
        issued_at: daysFromNow(-370),
        valid_from: daysFromNow(-370),
        valid_to: daysFromNow(6),
        payment_frequency: 'quarterly',
        next_payment_due: daysFromNow(4),
        next_check_due: daysFromNow(2),
        last_checked_at: daysFromNow(-28),
        last_check_result: 'warning',
        notes: 'Підготувати пакет документів на продовження до завершення строку дії.',
        created_at: daysFromNow(-370),
        updated_at: daysFromNow(-10),
        client: clients[2],
        responsible: profiles[1],
    },
    {
        id: 'lic-002',
        client_id: 'c-001',
        responsible_id: 'u-acc-001',
        type: 'transport_cargo',
        number: 'TR-C-44512',
        issuing_authority: 'Укртрансбезпека',
        place_of_activity: 'Київська обл., с. Проліски, логістичний хаб 3',
        status: 'active',
        issued_at: daysFromNow(-520),
        valid_from: daysFromNow(-520),
        valid_to: daysFromNow(24),
        payment_frequency: 'yearly',
        next_payment_due: daysFromNow(24),
        next_check_due: daysFromNow(40),
        last_checked_at: daysFromNow(-14),
        last_check_result: 'ok',
        notes: 'Контроль техоглядів автопарку ведеться окремо.',
        created_at: daysFromNow(-520),
        updated_at: daysFromNow(-5),
        client: clients[0],
        responsible: profiles[1],
    },
    {
        id: 'lic-003',
        client_id: 'c-009',
        responsible_id: 'u-acc-004',
        type: 'fuel_storage',
        number: 'FUEL-88911',
        issuing_authority: 'ГУ ДПС у Львівській обл.',
        place_of_activity: 'м. Львів, вул. Промислова, 24',
        status: 'expired',
        issued_at: daysFromNow(-430),
        valid_from: daysFromNow(-430),
        valid_to: daysFromNow(-2),
        payment_frequency: 'quarterly',
        next_payment_due: daysFromNow(-6),
        next_check_due: daysFromNow(-1),
        last_checked_at: daysFromNow(-95),
        last_check_result: 'mismatch',
        notes: 'Строк дії завершився. Потрібно негайно подати пакет на поновлення.',
        created_at: daysFromNow(-430),
        updated_at: daysFromNow(-2),
        client: clients[8],
        responsible: profiles[4],
    },
    {
        id: 'lic-004',
        client_id: 'c-004',
        responsible_id: 'u-acc-002',
        type: 'medical_practice',
        number: 'MED-10221',
        issuing_authority: 'МОЗ України',
        place_of_activity: 'м. Київ, вул. Ділова, 9',
        status: 'active',
        issued_at: daysFromNow(-620),
        valid_from: daysFromNow(-620),
        payment_frequency: 'quarterly',
        next_payment_due: daysFromNow(-1),
        next_check_due: daysFromNow(12),
        last_checked_at: daysFromNow(-20),
        last_check_result: 'ok',
        notes: 'Ліцензія безстрокова, контроль фокусується на поквартальних платежах.',
        created_at: daysFromNow(-620),
        updated_at: daysFromNow(-3),
        client: clients[3],
        responsible: profiles[2],
    },
    {
        id: 'lic-005',
        client_id: 'c-005',
        responsible_id: 'u-acc-003',
        type: 'transport_passenger',
        number: 'TR-P-33910',
        issuing_authority: 'Укртрансбезпека',
        place_of_activity: 'м. Київ, вул. Межигірська, 15',
        status: 'suspended',
        issued_at: daysFromNow(-300),
        valid_from: daysFromNow(-300),
        valid_to: daysFromNow(180),
        payment_frequency: 'yearly',
        next_payment_due: daysFromNow(175),
        next_check_due: daysFromNow(8),
        last_checked_at: daysFromNow(-45),
        last_check_result: 'warning',
        notes: 'Дія призупинена до усунення зауважень регулятора.',
        created_at: daysFromNow(-300),
        updated_at: daysFromNow(-7),
        client: clients[4],
        responsible: profiles[3],
    },
    {
        id: 'lic-006',
        client_id: 'c-008',
        responsible_id: 'u-acc-001',
        type: 'alcohol_wholesale',
        number: 'ALC-WS-77801',
        issuing_authority: 'ГУ ДПС у м. Києві',
        place_of_activity: 'м. Київ, вул. Лугова, 28',
        status: 'draft',
        issued_at: daysFromNow(-20),
        valid_from: daysFromNow(5),
        valid_to: daysFromNow(370),
        payment_frequency: 'quarterly',
        next_check_due: daysFromNow(16),
        last_check_result: 'not_checked',
        notes: 'Чернетка: очікуємо оригінал підтвердження від клієнта.',
        created_at: daysFromNow(-20),
        updated_at: daysFromNow(-1),
        client: clients[7],
        responsible: profiles[1],
    },
];

// ========== TASKS ==========
export const tasks: Task[] = [
    // ---- TO DO ----
    {
        id: 'TAX-102',
        client_id: 'c-001',
        title: 'Q3 VAT Declaration',
        description: 'Підготувати та подати декларацію з ПДВ за Q3 2023.',
        status: 'todo',
        type: 'tax_report',
        due_date: '2023-10-19T23:59:00Z',
        priority: 1,
        assignee_id: 'u-acc-001',
        created_by: 'u-admin-001',
        recurrence: 'quarterly',
        period: 'Q3 2023',
        proof_required: true,
        created_at: '2023-10-01T10:00:00Z',
        updated_at: '2023-10-18T10:00:00Z',
        client: clients[0],
        assignee: profiles[1],
        subtasks: [],
        comments: [],
        files: [],
    },
    {
        id: 'PAY-844',
        client_id: 'c-008',
        title: 'Monthly Payroll Calculation',
        description: 'Розрахувати зарплату за жовтень, подати звіт до ДПС.',
        status: 'todo',
        type: 'payroll',
        due_date: '2023-10-20T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-001',
        created_by: 'u-admin-001',
        recurrence: 'monthly',
        period: 'Жовтень 2023',
        proof_required: false,
        created_at: '2023-10-01T10:00:00Z',
        updated_at: '2023-10-17T10:00:00Z',
        client: clients[7],
        assignee: profiles[1],
        subtasks: [],
        comments: [],
        files: [],
    },
    {
        id: 'ONB-001',
        client_id: 'c-002',
        title: 'Initial Setup & Access',
        description: 'Отримати доступи до банк-клієнта, ДПС кабінету.',
        status: 'todo',
        type: 'onboarding',
        due_date: '2023-10-24T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-002',
        created_by: 'u-admin-001',
        recurrence: 'none',
        proof_required: false,
        created_at: '2023-10-15T10:00:00Z',
        updated_at: '2023-10-15T10:00:00Z',
        client: clients[1],
        assignee: profiles[2],
        subtasks: [],
        comments: [],
        files: [],
    },
    {
        id: 'TAX-110',
        client_id: 'c-005',
        title: 'Q3 Tax Filing 2023',
        description: 'Подати декларацію з прибутку за Q3.',
        status: 'todo',
        type: 'tax_report',
        due_date: '2023-10-22T23:59:00Z',
        priority: 1,
        assignee_id: 'u-acc-003',
        created_by: 'u-admin-001',
        recurrence: 'quarterly',
        period: 'Q3 2023',
        proof_required: true,
        created_at: '2023-10-01T10:00:00Z',
        updated_at: '2023-10-18T10:00:00Z',
        client: clients[4],
        assignee: profiles[3],
        subtasks: [],
        comments: [],
        files: [],
    },
    // ---- IN PROGRESS ----
    {
        id: 'REP-882',
        client_id: 'c-004',
        title: 'Q3 Grant Reporting',
        description: 'Підготувати звіт по грантовим коштам за Q3.',
        status: 'in_progress',
        type: 'tax_report',
        due_date: '2023-10-22T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-002',
        created_by: 'u-admin-001',
        recurrence: 'quarterly',
        period: 'Q3 2023',
        proof_required: true,
        created_at: '2023-10-01T10:00:00Z',
        updated_at: '2023-10-18T10:00:00Z',
        client: clients[3],
        assignee: profiles[2],
        subtasks: [],
        comments: [],
        files: [],
    },
    {
        id: 'TAX-185',
        client_id: 'c-009',
        title: 'VAT Correction Review',
        description: 'Перевірити коригування по ПДВ.',
        status: 'in_progress',
        type: 'tax_report',
        due_date: '2023-10-21T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-004',
        created_by: 'u-admin-001',
        recurrence: 'none',
        proof_required: false,
        created_at: '2023-10-10T10:00:00Z',
        updated_at: '2023-10-19T10:00:00Z',
        client: clients[8],
        assignee: profiles[4],
        subtasks: [],
        comments: [],
        files: [],
    },
    // ---- CLARIFICATION ----
    {
        id: 'INV-402',
        client_id: 'c-002',
        title: 'Missing Invoice #402',
        description: 'Клієнт не надав рахунок #402, потрібно уточнити.',
        status: 'clarification',
        type: 'reconciliation',
        due_date: '2023-10-23T23:59:00Z',
        priority: 1,
        assignee_id: 'u-acc-002',
        created_by: 'u-admin-001',
        recurrence: 'none',
        proof_required: true,
        created_at: '2023-10-12T10:00:00Z',
        updated_at: '2023-10-18T10:00:00Z',
        client: clients[1],
        assignee: profiles[2],
        subtasks: [],
        comments: [],
        files: [],
    },
    // ---- REVIEW ----
    {
        id: 'TAX-2023-Q3',
        client_id: 'c-001',
        title: 'Q3 Tax Report: Acme Corp LLC',
        description: 'Please prepare the quarterly tax filing for Acme Corp LLC. This client is on the 3rd Group FOP tax scheme (5%).\n\nEnsure all contractor invoices from September are fully reconciled before generating the declaration PDF. Double-check the currency exchange rates for the USD account transfers on Sept 12th and Sept 28th.',
        status: 'review',
        type: 'tax_report',
        due_date: '2023-10-20T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-001',
        created_by: 'u-admin-001',
        recurrence: 'quarterly',
        period: 'Q3 2023',
        proof_required: true,
        created_at: '2023-10-01T09:00:00Z',
        updated_at: '2023-10-18T10:30:00Z',
        client: clients[0],
        assignee: profiles[1],
        subtasks: [
            { id: 'st-001', task_id: 'TAX-2023-Q3', title: 'Reconcile Bank Statement (Monobank)', is_completed: true, sort_order: 1 },
            { id: 'st-002', task_id: 'TAX-2023-Q3', title: 'Verify 3rd Group Income Limits', is_completed: false, sort_order: 2 },
            { id: 'st-003', task_id: 'TAX-2023-Q3', title: 'Generate Declaration PDF & Sign', is_completed: false, sort_order: 3 },
        ],
        comments: [
            {
                id: 'cm-001',
                task_id: 'TAX-2023-Q3',
                author_id: 'u-acc-001',
                body: 'Missing invoice for Sept 20th ($450). I\'ve messaged the client on Telegram to request it.',
                created_at: '2023-10-18T10:30:00Z',
                author: profiles[1],
            },
        ],
        files: [],
    },
    // ---- DONE ----
    {
        id: 'PAY-830',
        client_id: 'c-003',
        title: 'September Payroll',
        description: 'Зарплата за вересень подана.',
        status: 'done',
        type: 'payroll',
        due_date: '2023-10-05T23:59:00Z',
        priority: 3,
        assignee_id: 'u-acc-001',
        created_by: 'u-admin-001',
        recurrence: 'monthly',
        period: 'Вересень 2023',
        proof_required: false,
        created_at: '2023-09-20T10:00:00Z',
        updated_at: '2023-10-04T10:00:00Z',
        client: clients[2],
        assignee: profiles[1],
        subtasks: [],
        comments: [],
        files: [],
    },
    {
        id: 'AUD-301',
        client_id: 'c-005',
        title: 'Monthly Audit Check',
        description: 'Щомісячна звірка документів.',
        status: 'done',
        type: 'audit',
        due_date: '2023-10-30T23:59:00Z',
        priority: 3,
        assignee_id: 'u-acc-004',
        created_by: 'u-admin-001',
        recurrence: 'monthly',
        period: 'Жовтень 2023',
        proof_required: false,
        created_at: '2023-10-01T10:00:00Z',
        updated_at: '2023-10-28T10:00:00Z',
        client: clients[4],
        assignee: profiles[4],
        subtasks: [],
        comments: [],
        files: [],
    },
    // ---- Additional tasks for capacity view ----
    {
        id: 'REC-501',
        client_id: 'c-009',
        title: 'Invoice Reconciliation',
        description: 'Звірка рахунків за жовтень.',
        status: 'todo',
        type: 'reconciliation',
        due_date: '2023-10-28T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-004',
        created_by: 'u-admin-001',
        recurrence: 'monthly',
        period: 'Жовтень 2023',
        proof_required: false,
        created_at: '2023-10-15T10:00:00Z',
        updated_at: '2023-10-15T10:00:00Z',
        client: clients[8],
        assignee: profiles[4],
        subtasks: [],
        comments: [],
        files: [],
    },
    {
        id: 'PAY-850',
        client_id: 'c-001',
        title: 'Payroll Verification',
        description: 'Верифікація зарплатної відомості.',
        status: 'review',
        type: 'payroll',
        due_date: '2023-10-27T23:59:00Z',
        priority: 2,
        assignee_id: 'u-acc-003',
        created_by: 'u-admin-001',
        recurrence: 'none',
        proof_required: true,
        created_at: '2023-10-16T10:00:00Z',
        updated_at: '2023-10-20T10:00:00Z',
        client: clients[0],
        assignee: profiles[3],
        subtasks: [],
        comments: [],
        files: [],
    },
];

// ========== ACTIVITY LOG ==========
export const activityLog: ActivityLogEntry[] = [
    {
        id: 'al-001',
        task_id: 'TAX-2023-Q3',
        actor_id: 'u-admin-001',
        action: 'Задачу створено',
        details: 'Автоматично згенеровано з шаблону.',
        created_at: '2023-10-18T09:00:00Z',
        actor: profiles[0],
    },
    {
        id: 'al-002',
        task_id: 'TAX-2023-Q3',
        actor_id: 'u-acc-001',
        action: 'Взято в роботу',
        created_at: '2023-10-18T10:15:00Z',
        actor: profiles[1],
    },
];

// ========== BILLING ==========
export const billingPlans: BillingPlan[] = [
    {
        id: 'bp-001',
        client_id: 'c-001',
        cadence: 'monthly',
        fee_minor: 480_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-365),
        updated_at: daysFromNow(-30),
        client: clients[0],
    },
    {
        id: 'bp-002',
        client_id: 'c-003',
        cadence: 'monthly',
        fee_minor: 320_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-260),
        updated_at: daysFromNow(-20),
        client: clients[2],
    },
    {
        id: 'bp-003',
        client_id: 'c-004',
        cadence: 'monthly',
        fee_minor: 450_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-180),
        updated_at: daysFromNow(-12),
        client: clients[3],
    },
    {
        id: 'bp-004',
        client_id: 'c-005',
        cadence: 'monthly',
        fee_minor: 390_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-220),
        updated_at: daysFromNow(-10),
        client: clients[4],
    },
    {
        id: 'bp-005',
        client_id: 'c-008',
        cadence: 'monthly',
        fee_minor: 280_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-140),
        updated_at: daysFromNow(-8),
        client: clients[7],
    },
    {
        id: 'bp-006',
        client_id: 'c-009',
        cadence: 'monthly',
        fee_minor: 720_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-400),
        updated_at: daysFromNow(-16),
        client: clients[8],
    },
    {
        id: 'bp-007',
        client_id: 'c-002',
        cadence: 'monthly',
        fee_minor: 250_000,
        currency: 'UAH',
        due_day: 10,
        is_active: true,
        created_at: daysFromNow(-90),
        updated_at: daysFromNow(-14),
        client: clients[1],
    },
];

export const invoices: Invoice[] = [
    {
        id: 'inv-001',
        client_id: 'c-001',
        billing_plan_id: 'bp-001',
        period: '2026-01',
        amount_due_minor: 480_000,
        amount_paid_minor: 480_000,
        currency: 'UAH',
        issued_at: daysFromNow(-34),
        due_date: daysFromNow(-20),
        status: 'paid',
        created_at: daysFromNow(-34),
        updated_at: daysFromNow(-18),
        client: clients[0],
        billing_plan: billingPlans[0],
    },
    {
        id: 'inv-002',
        client_id: 'c-001',
        billing_plan_id: 'bp-001',
        period: '2026-02',
        amount_due_minor: 480_000,
        amount_paid_minor: 240_000,
        currency: 'UAH',
        issued_at: daysFromNow(-18),
        due_date: daysFromNow(-5),
        status: 'overdue',
        created_at: daysFromNow(-18),
        updated_at: daysFromNow(-3),
        client: clients[0],
        billing_plan: billingPlans[0],
    },
    {
        id: 'inv-003',
        client_id: 'c-003',
        billing_plan_id: 'bp-002',
        period: '2026-02',
        amount_due_minor: 320_000,
        amount_paid_minor: 0,
        currency: 'UAH',
        issued_at: daysFromNow(-11),
        due_date: daysFromNow(6),
        status: 'sent',
        created_at: daysFromNow(-11),
        updated_at: daysFromNow(-11),
        client: clients[2],
        billing_plan: billingPlans[1],
    },
    {
        id: 'inv-004',
        client_id: 'c-004',
        billing_plan_id: 'bp-003',
        period: '2026-02',
        amount_due_minor: 450_000,
        amount_paid_minor: 450_000,
        currency: 'UAH',
        issued_at: daysFromNow(-13),
        due_date: daysFromNow(-2),
        status: 'paid',
        created_at: daysFromNow(-13),
        updated_at: daysFromNow(-1),
        client: clients[3],
        billing_plan: billingPlans[2],
    },
    {
        id: 'inv-005',
        client_id: 'c-005',
        billing_plan_id: 'bp-004',
        period: '2026-02',
        amount_due_minor: 390_000,
        amount_paid_minor: 100_000,
        currency: 'UAH',
        issued_at: daysFromNow(-16),
        due_date: daysFromNow(-1),
        status: 'overdue',
        created_at: daysFromNow(-16),
        updated_at: daysFromNow(-4),
        client: clients[4],
        billing_plan: billingPlans[3],
    },
    {
        id: 'inv-006',
        client_id: 'c-008',
        billing_plan_id: 'bp-005',
        period: '2026-02',
        amount_due_minor: 280_000,
        amount_paid_minor: 150_000,
        currency: 'UAH',
        issued_at: daysFromNow(-12),
        due_date: daysFromNow(10),
        status: 'partially_paid',
        created_at: daysFromNow(-12),
        updated_at: daysFromNow(-2),
        client: clients[7],
        billing_plan: billingPlans[4],
    },
    {
        id: 'inv-007',
        client_id: 'c-009',
        billing_plan_id: 'bp-006',
        period: '2026-02',
        amount_due_minor: 720_000,
        amount_paid_minor: 0,
        currency: 'UAH',
        issued_at: daysFromNow(-24),
        due_date: daysFromNow(-14),
        status: 'overdue',
        created_at: daysFromNow(-24),
        updated_at: daysFromNow(-14),
        client: clients[8],
        billing_plan: billingPlans[5],
    },
    {
        id: 'inv-008',
        client_id: 'c-002',
        billing_plan_id: 'bp-007',
        period: '2026-02',
        amount_due_minor: 250_000,
        amount_paid_minor: 0,
        currency: 'UAH',
        issued_at: daysFromNow(-3),
        due_date: daysFromNow(15),
        status: 'draft',
        created_at: daysFromNow(-3),
        updated_at: daysFromNow(-1),
        client: clients[1],
        billing_plan: billingPlans[6],
    },
];

export const payments: Payment[] = [
    {
        id: 'pay-001',
        client_id: 'c-001',
        amount_minor: 480_000,
        currency: 'UAH',
        paid_at: daysFromNow(-18),
        method: 'bank_transfer',
        status: 'received',
        external_ref: 'MTB-2026-01-1120',
        created_at: daysFromNow(-18),
        updated_at: daysFromNow(-18),
        client: clients[0],
    },
    {
        id: 'pay-002',
        client_id: 'c-001',
        amount_minor: 240_000,
        currency: 'UAH',
        paid_at: daysFromNow(-3),
        method: 'card',
        status: 'received',
        external_ref: 'MONO-2026-02-1804',
        created_at: daysFromNow(-3),
        updated_at: daysFromNow(-3),
        client: clients[0],
    },
    {
        id: 'pay-003',
        client_id: 'c-004',
        amount_minor: 450_000,
        currency: 'UAH',
        paid_at: daysFromNow(-1),
        method: 'bank_transfer',
        status: 'received',
        external_ref: 'PRIVAT-2026-02-0901',
        created_at: daysFromNow(-1),
        updated_at: daysFromNow(-1),
        client: clients[3],
    },
    {
        id: 'pay-004',
        client_id: 'c-005',
        amount_minor: 100_000,
        currency: 'UAH',
        paid_at: daysFromNow(-4),
        method: 'bank_transfer',
        status: 'received',
        external_ref: 'MTB-2026-02-2104',
        created_at: daysFromNow(-4),
        updated_at: daysFromNow(-4),
        client: clients[4],
    },
    {
        id: 'pay-005',
        client_id: 'c-008',
        amount_minor: 150_000,
        currency: 'UAH',
        paid_at: daysFromNow(-2),
        method: 'card',
        status: 'received',
        external_ref: 'MONO-2026-02-1177',
        created_at: daysFromNow(-2),
        updated_at: daysFromNow(-2),
        client: clients[7],
    },
    {
        id: 'pay-006',
        client_id: 'c-009',
        amount_minor: 720_000,
        currency: 'UAH',
        paid_at: daysFromNow(2),
        method: 'bank_transfer',
        status: 'pending',
        external_ref: 'PUMB-2026-02-5561',
        created_at: daysFromNow(-1),
        updated_at: daysFromNow(-1),
        client: clients[8],
    },
];

export const paymentAllocations: PaymentAllocation[] = [
    {
        id: 'alloc-001',
        payment_id: 'pay-001',
        invoice_id: 'inv-001',
        amount_minor: 480_000,
        created_at: daysFromNow(-18),
    },
    {
        id: 'alloc-002',
        payment_id: 'pay-002',
        invoice_id: 'inv-002',
        amount_minor: 240_000,
        created_at: daysFromNow(-3),
    },
    {
        id: 'alloc-003',
        payment_id: 'pay-003',
        invoice_id: 'inv-004',
        amount_minor: 450_000,
        created_at: daysFromNow(-1),
    },
    {
        id: 'alloc-004',
        payment_id: 'pay-004',
        invoice_id: 'inv-005',
        amount_minor: 100_000,
        created_at: daysFromNow(-4),
    },
    {
        id: 'alloc-005',
        payment_id: 'pay-005',
        invoice_id: 'inv-006',
        amount_minor: 150_000,
        created_at: daysFromNow(-2),
    },
];

// ========== HELPER FUNCTIONS ==========
export function getClientById(id: string): Client | undefined {
    return clients.find(c => c.id === id);
}

export function getProfileById(id: string): Profile | undefined {
    return profiles.find(p => p.id === id);
}

export function getTasksByStatus(status: string): Task[] {
    return tasks.filter(t => t.status === status);
}

export function getTasksByAssignee(assigneeId: string): Task[] {
    return tasks.filter(t => t.assignee_id === assigneeId);
}

export function getTasksByClient(clientId: string): Task[] {
    return tasks.filter(t => t.client_id === clientId);
}

export function getOverdueTasks(): Task[] {
    const now = new Date();
    return tasks.filter(t => t.status !== 'done' && new Date(t.due_date) < now);
}

export function getTasksDueToday(): Task[] {
    const now = new Date();
    const todayStr = now.toISOString().split('T')[0];
    return tasks.filter(t => t.due_date.startsWith(todayStr) && t.status !== 'done');
}
